import type { ServiceFeature, ServiceType } from "@/types/services-page";

export const SERVICE_TYPES: ServiceType[] = [
  {
    id: "corporate",
    title: "기업 홈페이지",
    description: "회사 소개와 서비스를 효과적으로 전달하는 기본 홈페이지입니다.",
    features: ["회사소개", "서비스", "포트폴리오", "문의하기"],
    industries: ["기업", "공장", "제조업", "건설"],
    previewImage: "/images/portfolio/mukhyang-long.webp",
    previewLabel: "기업 홈페이지",
    icon: "Building2",
  },
  {
    id: "hospital",
    title: "병원 홈페이지",
    description: "의료진 소개, 진료안내, 예약 문의를 한곳에서 제공합니다.",
    features: ["의료진", "진료과목", "오시는길", "예약문의"],
    industries: ["병원", "의원", "치과", "한의원"],
    previewImage: "/images/portfolio/arsene-long.webp",
    previewLabel: "병원 홈페이지",
    icon: "Hospital",
  },
  {
    id: "academy",
    title: "학원 홈페이지",
    description: "학부모가 필요한 정보를 쉽게 확인할 수 있도록 구성합니다.",
    features: ["강사진", "커리큘럼", "성적", "상담예약"],
    industries: ["학원", "교육", "어학원", "입시"],
    previewImage: "/images/portfolio/aone-long.webp",
    previewLabel: "학원 홈페이지",
    icon: "GraduationCap",
  },
  {
    id: "cafe",
    title: "카페·음식점",
    description: "메뉴 소개, 위치 안내, 예약과 문의가 가능합니다.",
    features: ["메뉴", "예약", "갤러리", "지도"],
    industries: ["카페", "음식점", "베이커리", "프랜차이즈"],
    previewImage: "/images/portfolio/steakhouse.webp",
    previewLabel: "카페·음식점",
    icon: "Coffee",
  },
  {
    id: "shop",
    title: "쇼핑몰",
    description: "온라인 주문과 결제가 가능한 쇼핑몰을 제작합니다.",
    features: ["상품관리", "장바구니", "결제", "주문조회"],
    industries: ["쇼핑몰", "브랜드", "소상공인", "D2C"],
    previewImage: "/images/services/shop.webp",
    previewLabel: "쇼핑몰",
    icon: "ShoppingBag",
  },
  {
    id: "landing",
    title: "랜딩페이지",
    description: "광고와 이벤트에 최적화된 전환 중심 페이지입니다.",
    features: ["CTA", "문의", "이벤트", "후기"],
    industries: ["광고", "이벤트", "프로모션", "스타트업"],
    previewImage: "/images/services/landing.webp",
    previewLabel: "랜딩페이지",
    icon: "Rocket",
  },
  {
    id: "booking",
    title: "예약 시스템",
    description: "온라인 예약과 일정 관리를 자동화합니다.",
    features: ["예약", "시간선택", "알림", "관리자"],
    industries: ["병원", "미용", "헬스", "상담"],
    previewImage: "/images/services/booking.webp",
    previewLabel: "예약 시스템",
    icon: "Calendar",
  },
  {
    id: "admin",
    title: "관리자 페이지",
    description: "공지, 문의, 회원, 콘텐츠를 직접 관리할 수 있습니다.",
    features: ["게시판", "회원관리", "문의관리", "콘텐츠"],
    industries: ["기업", "학원", "쇼핑몰", "SaaS"],
    previewImage: "/images/portfolio/admin.webp",
    previewLabel: "관리자 페이지",
    icon: "LayoutDashboard",
  },
  {
    id: "custom",
    title: "맞춤 개발",
    description: "기존 홈페이지로 해결되지 않는 기능을 직접 개발합니다.",
    features: ["CRM", "API", "자동화", "관리 시스템"],
    industries: ["스타트업", "기업", "SaaS", "플랫폼"],
    previewImage: "/images/portfolio/sajangman-long.webp",
    previewLabel: "맞춤 개발",
    icon: "Code2",
  },
];

export const SERVICE_FEATURES: ServiceFeature[] = [
  { id: "contact", label: "문의하기", description: "문의 폼으로 상담을 접수할 수 있습니다.", icon: "Mail" },
  { id: "board", label: "게시판", description: "공지사항과 소식을 게시할 수 있습니다.", icon: "Newspaper" },
  { id: "admin", label: "관리자 페이지", description: "콘텐츠와 문의를 직접 관리할 수 있습니다.", icon: "Shield" },
  { id: "booking", label: "예약 시스템", description: "온라인 예약 접수가 가능합니다.", icon: "Calendar" },
  { id: "signup", label: "회원가입", description: "회원 가입과 정보 관리가 가능합니다.", icon: "UserPlus" },
  { id: "login", label: "로그인", description: "회원 로그인과 인증이 가능합니다.", icon: "LogIn" },
  { id: "payment", label: "결제", description: "온라인 결제 연동이 가능합니다.", icon: "CreditCard" },
  { id: "map", label: "지도", description: "위치 안내와 지도 연동이 가능합니다.", icon: "MapPin" },
  { id: "sns", label: "SNS 연동", description: "소셜 미디어를 연결할 수 있습니다.", icon: "Share2" },
  { id: "seo", label: "SEO 최적화", description: "검색 노출을 고려한 구조로 제작합니다.", icon: "Search" },
  { id: "responsive", label: "반응형", description: "PC, 태블릿, 모바일에 최적화됩니다.", icon: "MonitorSmartphone" },
  { id: "upload", label: "파일 업로드", description: "파일과 이미지를 업로드할 수 있습니다.", icon: "Upload" },
];
